---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: Etc/UTC
    allow:
      # direct and indirect updates
      - dependency-type: "all"
    commit-message:
      prefix: chore
      include: scope
    groups:
      gomod:
        patterns:
          - "*"